### ISSUE TITLE
Add MEI download

### ISSUE THREAD

**Issue by eliocamp** [boshek/rsoi#17]
Data source is here: https://www.esrl.noaa.gov/psd/enso/mei/
And the data is hosted here: https://www.esrl.noaa.gov/psd/enso/mei/data/meiv2.data

If you'd like, I could implement `download_mei()`

**Comment by boshek** [comment]
This is a wonderful idea. I'd be happy to accept a PR for this but will ping you here if I start working on it before you do. This would really be a valuable contribution.
