### ISSUE TITLE
CurlTimeOut

### ISSUE THREAD

**Issue by HunterGleason** [boshek/rsoi#29]
When attempting to download enso data receive a 'curl::curl_fetch_memory(link)' error. Maybe missing required package? Using R 3.6.2 on Debian 10.

**Comment by boshek** [comment]
@HunterGleason can you please trying re-installing then post back a [reprex](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219)?

**Comment by HunterGleason** [comment]
Hi Sam,

Haha, was not expecting a response so soon! Will do!

Its probably just some package I missing or something? I’m not terribly familiar with curl, let alone in R.

I’ll let you know how it goes.

Thanks!

Hunter

**Comment by HunterGleason** [comment]
Hi Sam,

Still get the error.

I think I found the culprit, in your ‘check_responce’ function the curl::curl_fetch_memory(link) call returns the error ‘Error in curl::curl_fetch_memory(link) :  Timeout was reached: [www.cpc.ncep.noaa.gov] Resolving timed out after 10000 milliseconds’. I’ll google see what I can figure out on this error, I am pretty naive when it comes to curl.

Definitely no urgency on this issue so don’t feel like you got to fix this right now.

Hunter

**Comment by HunterGleason** [comment]
Aha! So apparently for us who have slow DNS servers increasing the timeout threshold of the curl handle will fix the issue of the curl::curl_fetch_memory(link) function returning a error. A threshold of 60 sec seemed to do it for my connection. *Note I am currently NoMachined into the desktop remotely, might also be part of the problem. 
https://github.com/boshek/rsoi/commit/98b2c06fc699683775ff31475d4679b65d1ea854**
