### ISSUE TITLE
Do you want to start importing the PDO?

### ISSUE THREAD

**Issue by joethorley** [boshek/rsoi#31]
The mechanism by which rpdo has been obtaining the Pacific Decadal Oscillation has changed from a website that is no longer being updated to 

 https://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_OC_PDO.html

Rather than have me recode rpdo are you interested in taking this on?

**Comment by boshek** [comment]
Maybe? Do you mean just add a url like this?

https://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_OC_PDO.htmlTable?time%2CPDO&time%3E=1950-12-25T00%3A00%3A00Z&time%3C=2020-01-01T00%3A00%3A00Z

**Comment by joethorley** [comment]
Whatever works for best for you - rsoi just seems like the natural place to house the PDO?

**Comment by boshek** [comment]
@eliocamp has done this @joethorley. What are you plans for rpdo? Is there any sense is giving it a release to push folks to this package?

**Comment by joethorley** [comment]
Yes I think it should be become https://www.tidyverse.org/lifecycle/#superseded and it should direct folks to rsoi I'll attempt to get to in the next week.

**Comment by joethorley** [comment]
Done https://github.com/poissonconsulting/rpdo

**Comment by eliocamp** [comment]
I never researched the PDO. What's the difference between that index and this one: https://www.ncdc.noaa.gov/teleconnections/pdo/ ? Should the package serve both indices?

**Comment by joethorley** [comment]
Good question - I'm not an expert but seeing as Mantua is a co-author on rpdo I would suspect that rpdo provided the Mantua PDO

> The NCEI PDO index is based on NOAA's extended reconstruction of SSTs (ERSST Version 4). It is constructed by regressing the ERSST anomalies against the Mantua PDO index for their overlap period, to compute a PDO regression map for the North Pacific ERSST anomalies. The ERSST anomalies are then projected onto that map to compute the NCEI index. The NCEI PDO index closely follows the Mantua PDO index.

I would have thought that the rsoi should provide both.

**Comment by boshek** [comment]
Closed via #33
