### ISSUE TITLE
Error for the function, download_pdo()

### ISSUE THREAD

**Issue by yfhuang7** [boshek/rsoi#38]
Hi,

I really apprciate your R package to grab climate indices! It was working great at beginning (the end of last month), but I met this error now when I used: 

> Error in charToDate(x) : 
  character string is not in a standard unambiguous format

Note: I ended up just downloading the PDO index from the cciea_OC_PDO.html webpage.  I'm not rushing to get this issue resolved, but just FYI that this error started showing up.

**Comment by boshek** [comment]
Thanks for the report. rsoi is a but of mess right now as it isn't even on CRAN. I will sort it all out ASAP.

**Comment by boshek** [comment]
Back on CRAN now. @yfhuang7 are you still experiencing this error? Can you provide a [reprex](https://www.tidyverse.org/help/)?

**Comment by yfhuang7** [comment]
Hi, sorry for the late response. I was away from this project. But I check again, it works now! Thanks!
