### ISSUE TITLE
Add asymmetric SAM index

### ISSUE THREAD

**Issue by eliocamp** [boshek/rsoi#47]
This is a bit of a conflict of interests, but my PhD advisors and I published [a paper](https://doi.org/10.1007/s00382-021-05896-5) that splits the Southern Annular Mode (aka AAO) into a symmetric and an asymmetric part. I'm now setting up everything to make the data available [on my institution's website](http://www.cima.fcen.uba.ar/~elio.campitelli/asymsam/get-data/) in daily and monthly time series updated monthly. 

A function to retrieve these data might be relevant to the package. OTOH, these indices are far from established in the literature, so it might be a bit of an overreach. There are a million different atmospheric indices around and one more is born every day, so it would make sense to wait until an index is widely used before adding it to the package. What are your thoughts on this?

**Comment by boshek** [comment]
Oh I say 100% include. We _could_ put some guardrails around this. For sure we can add a paper citation to the documentation and maybe even output a once per session message mentioning the citation or something like that. 

Plus since my name is Sam, we are both in a conflict of interest ;)

**Comment by eliocamp** [comment]
Ok! 
I'll wait a bit until IT sets everything up in a more permanent URL and then reate a PR.
